import Head from 'next/head'
import NavBar from "../components/nav";

export default function Home() {
    return (
        <div>
            <Head>
                <title>NextJS Login Example</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <NavBar/>

            <h1>I didn't feel like making this page</h1>

        </div>
    )
}
